name: Get Process Info
id: bc91a8cf-35e7-4bb2-8140-e756cc06fd71
tags:
description: This playbook and search queries the Endpoint data model to give you details about the process running on a host which is under investigation. To gather the process info, enter the values for the process name in question and the destination IP address.
inputs:
- process_name
- dest
search: '| tstats `summariesonly` count values(Processes.process) as process min(_time)
    as firstTime max(_time) as lastTime FROM datamodel=Endpoint.Processes by Processes.user Processes.parent_process_name Processes.process_name Processes.dest
| `drop_dm_object_name("Processes")`
| search  process_name= $process_name$
| search dest = $dest$
| `security_content_ctime(firstTime)`
| `security_content_ctime(lastTime)`'
automation:
  role:
  sla_type: minutes
  sla:
  is_note_required: false
  actions:
    - run query
  playbooks:
    - scm: escu
      playook: Get process information
references:
  - Blue Team Handbook by Don Murdoch, Chapter 4 Host based Analysis 4.1 Indicators of Compromise page 60
how_to_implement: To successfully implement this search you must be ingesting endpoint
  data and populating the Endpoint data model.
version: 2
date: '2019-04-01'
author: Bhavin Patel, Splunk
